.catalog:
  name: "Etcd"
  version: "2.2.1-rancher1"
  description: |
    (Experimental)Distributed reliable key-value store
  minimum_rancher_version: "v0.46.0"
  questions:
    - variable: "scale"
      description: "Number of Etcd nodes"
      label: "Number of Nodes:"
      required: true
      default: 1
      type: "int"
etcd:
  scale: "${scale}"
